DS-424 Add the Membership Calculator block to Layout Builder
YCloudYUSA/yusaopeny_memberships pull request #1
Opened 2023-03-29 13:30 UTC by aleevas

Issue: [DS-424](https://yusa.atlassian.net/browse/DS-424)

The PR provides the ability to add the Membership Calculator block to the LB.

How it looks like:
![DS-424-AddBlock](https://user-images.githubusercontent.com/744406/228307667-fab784c2-8cf4-43dc-ad1d-b1aa3c140e64.png)
![DS-424-ConfigureBlock](https://user-images.githubusercontent.com/744406/228307700-930e060d-a2ae-472f-80d0-e8cfa4c3c208.png)
In LB the Membership app doesn't initial properly after block changes (needs to reload the page), so we use a placeholder instead empty space

![DS-424-LBplaceholder](https://user-images.githubusercontent.com/744406/228307716-5f610ebd-314c-4bc2-8c88-13a5d5eebaf1.png)
On front:

![DS-424-MembershipCalcFront](https://user-images.githubusercontent.com/744406/228307732-3fae08b3-0af8-49e7-aa11-80172dff3f1d.png)

2023-03-30 08:05 UTC, mkdok commented on modules/lb_membership_calculator/config/install/field.field.block_content.lb_membership_calculator.field_block.yml
> +description: ''
Please add description

2023-03-30 08:11 UTC, aleevas commented on modules/lb_membership_calculator/config/install/field.field.block_content.lb_membership_calculator.field_block.yml
> +description: ''
done

2023-03-30 08:16 UTC, podarok commented on modules/lb_membership_calculator/lb_membership_calculator.info.yml
> +description: 'Helper module to show "Membership Calculator" block in Layout Builder.'
Let's have a README.md with how to install this piece
https://github.com/YCloudYUSA/yusaopeny_memberships#installation

Remember, membership framework is not a default distribution compinent. Would be great @froboy to jump in with some ideas
We can't have membership calculator in a distribution by  default

2023-03-30 08:30 UTC, podarok requested changes
A few suggestions to approve and discussion points for @froboy

2023-03-30 08:30 UTC, podarok commented on modules/lb_membership_calculator/lb_membership_calculator.info.yml
> +  - layout_builder
```suggestion
  - drupal:block_content
  - drupal:layout_builder
```

2023-03-30 08:30 UTC, podarok commented on modules/lb_membership_calculator/config/install/field.field.block_content.lb_membership_calculator.field_block.yml
> +      label: 'Membership Calculator'
Let's talk about naming. We have Membership Calculator and Membership Builder ( or Membership Framework )
Let's discuss how we should name it going forward to avoid confusion within a community @froboy

2023-04-03 08:43 UTC, merged

2023-04-03 19:42 UTC, froboy commented
@podarok I would have preferred if we waited to merge this until the pending questions were worked out. There was definitely some confusion here that shouldn't have been committed until it was resolved.

2023-04-04 07:49 UTC, podarok commented
> @podarok I would have preferred if we waited to merge this until the pending questions were worked out. There was definitely some confusion here that shouldn't have been committed until it was resolved.

I've merged in order to avoid loosing from our radars, but not tagged with a release

Let's discuss and apply a fix on top of this
@froboy @aleevas